version: "2"

services:
  app:
    build: .
    image: micropython-esp32
    volumes:
      - ./devicefs:/app/devicefs
      - ./scripts:/app/scripts
      - ./firmware:/app/firmware
    stdin_open: true
    tty: true
