version: "2"

services:
  app:
    build: .
    image: ${FLAVOUR}-docker
    container_name: ${FLAVOUR}-docker
    volumes:
      - ./devicefs:/app/devicefs
      - ./scripts:/app/scripts
    stdin_open: true
    tty: true
